### ISSUE TITLE
ToString method does not convert correctly array elements

### ISSUE THREAD

**Issue by cristinamudura** [nexxbiz/JLio#65]
Transformation Script

```json
[
  {
    "path": "$.myObject.newProperty",
    "value": [
      {
        "test": 3,
        "something": "1"
      },
      {
        "test": 5,
        "something": "1"
      }
    ],
    "command": "add"
  },
  {
    "path": "$.myObject.newProperty[*].test",
    "value": "=toString($.myObject.newProperty[*].test)",
    "command": "set"
  }
]
```

Current Result
```json
{
  "newProperty": [
    {
      "test": "[\n  3,\n  5\n]",
      "something": "1"
    },
    {
      "test": "[\n  \"[\\n  3,\\n  5\\n]\",\n  5\n]",
      "something": "1"
    }
  ]
}
```

Expected result
```json
{
  "newProperty": [
    {
      "test": "3",
      "something": "1"
    },
    {
      "test": "5",
      "something": "1"
    }
  ]
}
```

This works only when the array has a single element

**Comment by FransVanEk** [comment]
Well, the way you constructed the script means that for each item in the array you want to replace the test property value with any value selected by the path. This will result in all the elements in the array, and those will become the new value. 

since this is not your intended result, you can simply use the toString() without the parameters. 

this will just convert the current value into a string. And that matches your desired outcome
